#server:
#  port: 8082 # Unique port for user-service
#
#spring:
#  application:
#    name: user-service # This name will be used in Eureka registry
#  profiles:
#    active: dev
#  main:
#    allow-bean-definition-overriding: true
#  r2dbc:
#    url: r2dbc:postgresql://127.0.0.1:5432/clubs_db
#    username: postgres_user
#    password: postgres_password
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true # Crucial for proper registration
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#  client:
#    enabled: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ # Point to your Eureka server
#    fetch-registry: true
#    register-with-eureka: true
#
#application:
#  security:
#    jwt:
#      secret-key: ${JWT_SECRET}
#
#
##logging:
##  level:
##    org.springframework.r2dbc: DEBUG

# services/user-service/src/main/resources/application.yml
spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT:5432}/${DB_NAME:tclubsdb}
    username: ${DB_USER:tclubs}
    password: ${DB_PASSWORD:tclubs-pass}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
      register-with-eureka: true
      fetch-registry: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
