server:
  port: 8085 # Or any other unique port

spring:
  application:
    name: dummy-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # Crucial for proper registration
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true