server:
  port: 8761 # Default Eureka server port

spring:
  application:
    name: eureka-server # The name of your Eureka server application

eureka:
  instance:
    hostname: localhost # For local development
  client:
    register-with-eureka: false # Eureka server itself should not register with itself
    fetch-registry: false # Eureka server does not need to fetch the registry from itself
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # Eureka server URL

logging:
  level:
    com.netflix.eureka: OFF # Reduce noisy Eureka logs
    com.netflix.discovery: OFF